name: Build and Deploy Resume

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex

      - name: Rename PDF for recruiters
        run: mv main.pdf Dalia_Elsayed_resume.pdf

      - name: Move 'latest' tag to current commit
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git tag -f latest
          git push -f origin latest

      - name: Create or Update GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: Latest Resume
          files: Dalia_Elsayed_resume.pdf # Ensure this matches the renamed file above
          make_latest: true
